blank_issues_enabled: false
contact_links:
  - name: Project tracking template
    url: https://github.com/ibloud/kujo-beatdown-beatsaber-map/blob/main/docs/parent-tracking-issue.md
    about: Use this tracking template to manage roadmap and sub-issues.
